name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: harshv834/academic_website@master
      env:
        HUGO_VERSION: 0.68.3
        TARGET_REPO: harshv834/harshv834.github.io
        TOKEN: ${{ secrets.TOKEN }}

